<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "title": "CoGU",
    "slogan": "Welcome to Bludit",
    "description": "Congratulations you have successfully installed your Bludit.",
    "footer": "Copyright \u00a9 2025",
    "itemsPerPage": 6,
    "language": "en",
    "locale": "en, en_US, en_AU, en_CA, en_GB, en_IE, en_NZ",
    "timezone": "Europe\/Stockholm",
    "theme": "marble",
    "adminTheme": "booty",
    "homepage": "",
    "pageNotFound": "",
    "uriPage": "\/",
    "uriTag": "\/tag\/",
    "uriCategory": "\/category\/",
    "uriBlog": "",
    "url": "http:\/\/localhost:8000",
    "emailFrom": "no-reply@localhost:8000",
    "orderBy": "position",
    "currentBuild": 20240806,
    "twitter": "https:\/\/twitter.com\/bludit",
    "facebook": "https:\/\/www.facebook.com\/bluditcms",
    "codepen": "",
    "github": "https:\/\/github.com\/bludit",
    "instagram": "",
    "gitlab": "",
    "linkedin": "",
    "xing": "",
    "telegram": "",
    "dateFormat": "F j, Y",
    "extremeFriendly": true,
    "autosaveInterval": 2,
    "titleFormatHomepage": "{{site-slogan}} | {{site-title}}",
    "titleFormatPages": "{{page-title}} | {{site-title}}",
    "titleFormatCategory": "{{category-name}} | {{site-title}}",
    "titleFormatTag": "{{tag-name}} | {{site-title}}",
    "imageRestrict": true,
    "imageRelativeToAbsolute": false,
    "mastodon": "",
    "dribbble": "",
    "vk": "",
    "thumbnailWidth": 400,
    "thumbnailHeight": 400,
    "thumbnailQuality": 100,
    "markdownParser": true,
    "customFields": "[]"
}